# Generated by Django 5.0.7 on 2024-08-04 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JenjangDanKelas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jenjang_kelas', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Jenjang dan Kelas',
                'ordering': ['nama_jenjang_kelas'],
            },
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mata_pelajaran', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/logo_sekolah/')),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mata_pelajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.matapelajaran')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sekolah')),
            ],
        ),
        migrations.CreateModel(
            name='PerangkatKurikulum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pk', models.CharField(max_length=100)),
                ('file_pk', models.FileField(upload_to='media/PK/')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guru')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.matapelajaran')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sekolah')),
            ],
        ),
        migrations.CreateModel(
            name='MateriGuru',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_materi', models.CharField(max_length=100)),
                ('file_materi', models.FileField(upload_to='media/materi/')),
                ('cover_image', models.ImageField(blank=True, editable=False, null=True, upload_to='media/materi_covers/')),
                ('status', models.BooleanField(choices=[(True, 'Aktif'), (False, 'Tidak Aktif')], default=False, null=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jenjangdankelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.matapelajaran')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sekolah')),
            ],
        ),
        migrations.CreateModel(
            name='FlipPDF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='temp_zip')),
                ('index_file', models.CharField(blank=True, editable=False, max_length=255)),
                ('cover_file', models.CharField(blank=True, editable=False, max_length=255)),
                ('status', models.BooleanField(choices=[(True, 'Aktif'), (False, 'Tidak Aktif')], default=False)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jenjangdankelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.matapelajaran')),
                ('untuk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sekolah')),
            ],
            options={
                'verbose_name': 'FlipPDF',
                'verbose_name_plural': 'FlipPDF',
            },
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_buku', models.CharField(max_length=255)),
                ('file_buku', models.FileField(upload_to='media/buku/')),
                ('penerbit', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(blank=True, editable=False, null=True, upload_to='media/buku_covers/')),
                ('status', models.BooleanField(choices=[(True, 'Aktif'), (False, 'Tidak Aktif')], default=False)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jenjangdankelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.matapelajaran')),
                ('untuk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sekolah')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jenjangdankelas')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sekolah')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
