# Generated by Django 5.0.7 on 2024-08-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='jenjang',
            field=models.ManyToManyField(to='app.jenjangdankelas'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='cover_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='buku_covers'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='file_buku',
            field=models.FileField(upload_to='buku'),
        ),
        migrations.AlterField(
            model_name='materiguru',
            name='cover_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='materi_covers/'),
        ),
        migrations.AlterField(
            model_name='materiguru',
            name='file_materi',
            field=models.FileField(upload_to='materi/'),
        ),
        migrations.AlterField(
            model_name='perangkatkurikulum',
            name='file_pk',
            field=models.FileField(upload_to='PK/'),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_sekolah/'),
        ),
    ]
